### ISSUE TITLE
Add comment-functionality

### ISSUE THREAD

**Issue by smpar** [vkosuri/gedit-robot#1]
Hello,
would it be possible to add comment functionality in lang-robot file?
Because if we add the hash (#) character in front of a line, the colour of the sentence isn't changed.

**Comment by vkosuri** [comment]
Thanks, I think your issue was fixed. Let me know if it fails

![gedit-robot-lang](https://cloud.githubusercontent.com/assets/13664257/15142227/c7bd5632-16c1-11e6-9069-03893ea20005.png)

**Comment by smpar** [comment]
Yes, works fine.
Thank you.

**Comment by vkosuri** [comment]
Thank you cheers :)
